### ISSUE TITLE
Add Apple Podcasts scraping ability

### ISSUE THREAD

**Issue by si266** [cowboy-bebug/app-store-scraper#13]
Hey,

Just wanted to say that I "repurposed" a bit your scraper so that I can scrape Apple Podcasts reviews as the website is 99% similar to the App Store.

Example: https://podcasts.apple.com/us/podcast/the-npr-politics-podcast/id1057255460#see-all/reviews

**By changing this:**

     __landing_path = "{country}/apps/{app_name}/id{app_id}"
     __request_path = "v1/catalog/{country}/app/{app_id}/reviews"

**To this:**

    __landing_path = "{country}/podcast/{app_name}/id{app_id}"
    __request_path = "v1/catalog/{country}/podcasts/{app_id}/reviews"

**and** 

    __landing_host = "apps.apple.com"
    __request_host = "amp-api.apps.apple.com"

**To this:**
    __landing_host = "podcasts.apple.com"
    __request_host = "amp-api.podcasts.apple.com"

**And not using attribute "isEdited"** because its not available in the Podcasts

I'm able to scrape podcasts reviews with your Scraper!

There was no other way to contact you, and I thought you might find it cool and decide to implement it :)

**Comment by cowboy-bebug** [comment]
Hey @si266!

Nice job. Really appreciate you sharing this!
I'll implement it for sure 👍 

Happy hacking :)
