### ISSUE TITLE
features request

### ISSUE THREAD

**Issue by WenchenLi** [cowboy-bebug/app-store-scraper#16]
hi thank you for this code base, a quick question and sorry to post it here:
is it possible to add feature scrape review after certain date, say review after 9/2/2020?

thanks

**Comment by cowboy-bebug** [comment]
Hey! Apologies for the late response.

The feature could be added but one issue with the App Store reviews is that they are not ordered by date.
So I think it's best to grab all the reviews and persist them in a database or as a flat file -> and then filter by date.
