### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ianyy93** [cowboy-bebug/app-store-scraper#17]
Sorry for this silly question, I am new to Python

Running the below codes and resulted in the captioned error message:

```
from app_store_scraper import AppStore
from pprint import pprint
import csv

alipayhk = AppStore(country="hk", app_name="alipayhk")
alipayhk.review()

#pprint(alipayhk.reviews)
pprint(alipayhk.reviews_count)

csv_columns = ['date', 'developerResponse', 'isEdited','rating','review','title','userName']
csv_data = alipayhk.reviews
with open('alipayhk.csv', mode='w', newline='', encoding='utf-8-sig') as csvlist:
    writer = csv.DictWriter(csvlist, fieldnames=csv_columns)
    writer.writeheader()
    for data in csv_data:
        writer.writerow(data)
```

May I know what is causing this error please? Thanks loads

**Comment by cowboy-bebug** [comment]
Hey sorry for the late response!

It looks like it works on my machine and couldn't reproduce the error:
<img width="1077" alt="Screen Shot 2020-09-29 at 9 29 17 AM" src="https://user-images.githubusercontent.com/6591791/94482767-4c81da00-0236-11eb-89a9-e3ce78fb37af.png">
