### ISSUE TITLE
Regex pattern search fail

### ISSUE THREAD

**Issue by espisangijo** [cowboy-bebug/app-store-scraper#18]
```
app_id = re.search(pattern, self.__response.text).group(1)
```
This line results in the following error:
`AttributeError: 'NoneType' object has no attribute 'group'`

This error was by following the given example.
```
fortnite = AppStore(country="nz", app_name="fortnite")
```

**Comment by cowboy-bebug** [comment]
Hey there apologies for the late response!
Apple recently removed Fortnite from the App Store. So I'll update the example using Minecraft.
