### ISSUE TITLE
Pull Latest Reviews

### ISSUE THREAD

**Issue by johnwessolomon88** [cowboy-bebug/app-store-scraper#24]
This is more of a question than an "issue", but do you know how to get the app store API to sort by most recent? If you know the right API param(s) to make that happen, I'll be happy to branch it and do a PR for you.

**Comment by cowboy-bebug** [comment]
No I couldn't find a query parameter (or any buttons) for sorting. My approach would be to download all the reviews for an app and then sort them. It's not ideal but I'm not sure of any other way.

**Comment by johnwessolomon88** [comment]
https://gist.github.com/kgn/e96e7ae71a38447ac614

I found something that may have revealed a way. I have not tested it yet. Once I get some time bandwidth I will.

**Comment by cowboy-bebug** [comment]
That API didn't give me all the data I needed if I recall correctly. I'll close this issue for now.
