### ISSUE TITLE
Add sleep interval to avoid 429 status code

### ISSUE THREAD

**Issue by yu-iskw** [cowboy-bebug/app-store-scraper#25]
## Motivation
Thank you for the great module.
I was sometimes faced with 429 status code, when I scraped more than 10,000 reviews. So, it would be nice to take an interval to call `GET` to avoid 429 status code.

## Expected features
For instance, if we want to take 10 seconds between calling `GET` methods, we can put the options like below.
```python
app_store = AppStore(country="us", app_name="...", sleep_interval=10)
```

**Comment by cowboy-bebug** [comment]
Hi 👋 

Thanks for raising an issue! This is implemented in this PR: https://github.com/cowboy-bebug/app-store-scraper/pull/26. Using the above example, something like this can be done:
```python
app_store = AppStore(country="us", app_name="...")
app_store.review(sleep=10)
```

**Comment by yu-iskw** [comment]
@cowboy-bebug Thank you for quickly implementing the feature!

**Comment by cowboy-bebug** [comment]
Let me know if there are any other feature requests 😄

**Comment by AdityaJ42** [comment]
Hello
Thank you for this feature to avoid the 429 status code. However, when the sleep interval is set to lower durations (upto 5 seconds), after a certain point the error pops up. And setting a higher sleep interval takes too long to fetch reviews for apps, irrespective of the number of reviews. Is there any workaround to this?
