### ISSUE TITLE
Only scrappig 6133 reviews

### ISSUE THREAD

**Issue by deepak2431** [cowboy-bebug/app-store-scraper#28]
I am trying to scrap the reviws of Slack app but the scrapper stops after scrapping 6133 reviews. Is it limited by this package?
Link to the URL: https://apps.apple.com/us/app/slack/id618783545

**Comment by tphuonglam82** [comment]
This mean Review on Apple store inlcude rating and review, this 6133 reviews is only review.

**Comment by tphuonglam82** [comment]
@cowboy-bebug How to know total review before crawling? Thanks @cowboy-bebug

**Comment by deepak2431** [comment]
@tphuonglam82 It's mentioned after opening the link that the total reviews are 11.8k. I think that there might be more than 6133 reviews to scrap it.

**Comment by tphuonglam82** [comment]
yeah, this review may be have reply and crawler not crawling this reply, i have check duplicaed record when crawed @deepak2431

**Comment by Gabriel1443** [comment]
~~@deepak2431 From my experience total review counts on the page is cross-regioned. 
The url: [https://apps.apple.com/us/app/slack/id618783545](https://apps.apple.com/us/app/slack/id618783545) only contains reviews from the US region.~~

Sorry you are right! Rating number is not cross-regioned!

**Comment by cowboy-bebug** [comment]
Hey @tphuonglam82 @deepak2431
There isn't a way to tell how many reviews exist for an app.

Also the numbers of ratings and reviews are not equal -> there are more ratings than reviews most of the time (because people rate apps but leave out writing reviews)

---

And thanks for the comment! @Gabriel1443
