### ISSUE TITLE
How check total review before crawling?

### ISSUE THREAD

**Issue by tphuonglam82** [cowboy-bebug/app-store-scraper#29]
Dear @cowboy-bebug ,
I want to know total review before crawling because i want to split the review to file,Ex: Job 1 crawling from 1: 100-->write to file 001
Job 2 crawling from 101:200-->write to file 002 
Many thanks @cowboy-bebug

**Comment by cowboy-bebug** [comment]
Hey @tphuonglam82,

I don't think there is a way for us at the moment (I'm sure there are internal APIs but they aren't available to us 😄)
Also see https://github.com/cowboy-bebug/app-store-scraper/issues/28#issuecomment-741288533

Thanks!
